In [1]:
# dependencies
import pandas as pd
import numpy as np
import os
from datetime import datetime

In [2]:
#load conflicts csv
conflicts = os.path.join("1900-01-01-2018-02-20.csv")

In [3]:
conflicts_df = pd.read_csv(conflicts)

In [4]:
conflicts_df.head()

,data_id,iso,event_id_cnty,event_id_no_cnty,event_date,year,time_precision,event_type,actor1,assoc_actor_1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3
0,686727,792,TUR1469,1469.0,17/02/2018,2018,2,Remote violence,PKK: Kurdistan Workers Party,NaN,...,Semdinli,37.3051,44.5742,2,Beyaz Gazete,Subnational,"Reported on Saturday, 17 Febraury 2017, 1 Turk...",1,1519072933,TUR
1,685529,180,DRC11980,11980.0,17/02/2018,2018,1,Violence against civilians,ADF: Allied Democratic Forces,NaN,...,Eringiti,0.8519,29.6124,1,Agence France Presse; Xinhua,International,5 people were killed during an ambush on a civ...,5,1519056479,COD
2,685530,180,DRC11979,11979.0,17/02/2018,2018,1,Riots/Protests,Rioters (Democratic Republic of Congo),NaN,...,Ango,4.0296,25.8471,1,Radio Okapi,Subnational,"On February 17, the population from Ango rebel...",0,1519056479,COD
3,685686,434,LBY6702,6702.0,17/02/2018,2018,1,Remote violence,Unidentified Armed Group (Libya),NaN,...,Buatni,32.0984,20.1767,1,Alwasat,National,Four civilians were wounded by the explosion o...,0,1519056480,LBY
4,685687,434,LBY6703,6703.0,17/02/2018,2018,1,Violence against civilians,Unidentified Armed Group (Libya),NaN,...,Jalu,29.0333,21.5500,2,Alwasat,National,Unknown gunmen set up a fake checkpoint and ab...,0,1519056480,LBY

In [5]:
#column headers for dataframe
list(conflicts_df)

['data_id',
 'iso',
 'event_id_cnty',
 'event_id_no_cnty',
 'event_date',
 'year',
 'time_precision',
 'event_type',
 'actor1',
 'assoc_actor_1',
 'inter1',
 'actor2',
 'assoc_actor_2',
 'inter2',
 'interaction',
 'region',
 'country',
 'admin1',
 'admin2',
 'admin3',
 'location',
 'latitude',
 'longitude',
 'geo_precision',
 'source',
 'source_scale',
 'notes',
 'fatalities',
 'timestamp',
 'iso3']

In [6]:
# find the oldest and newest entries of the data
conflicts_df['event_date'] = pd.to_datetime(conflicts_df['event_date'])
oldest_date = conflicts_df['event_date'].min()
newest_date = conflicts_df['event_date'].max()
print(oldest_date)
print(newest_date)

1997-01-01 00:00:00
2018-12-02 00:00:00

In [7]:
# Identify the conflict types 
types = conflicts_df['event_type'].unique()
print(types)

['Remote violence' 'Violence against civilians' 'Riots/Protests'
 'Battle-No change of territory' 'Strategic development'
 'Battle-no change of territory' 'Non-violent transfer of territory'
 'Battle-Non-state actor overtakes territory'
 'Battle-Government regains territory' 'Headquarters or base established'
 'Riots/Protests ' 'Non-violent Transfer of Territory' 'Remote Violence'
 'Violence Against Civilians' 'Battle-Government regains territory '
 'Battle-Non-state actor overtakes territory ' 'Remote violence '
 'Violence against civilians ' 'Battle-No change of territory '
 'Strategic development ' 'Non-violent transfer of territory ']

In [8]:
# What countries are included in the data
types = conflicts_df['country'].unique()
print(types)

['Turkey' 'Democratic Republic of Congo' 'Libya' 'Mali' 'Sudan' 'Egypt'
 'Afghanistan' 'Iraq' 'Palestine' 'Yemen' 'Algeria' 'Ethiopia'
 'Ivory Coast' 'Kenya' 'Nigeria' 'Senegal' 'Somalia' 'South Africa'
 'Zimbabwe' 'Tunisia' 'Uganda' 'Tanzania' 'Burkina Faso' 'Pakistan'
 'Israel' 'Jordan' 'Saudi Arabia' 'Central African Republic' 'Madagascar'
 'Morocco' 'South Sudan' 'Iran' 'Benin' 'Liberia' 'Bahrain' 'Rwanda' 'Chad'
 'Guinea' 'Lebanon' 'Cameroon' 'Niger' 'Zambia' 'Burundi' 'Mozambique'
 'Ghana' 'Bangladesh' 'Mauritania' 'Equatorial Guinea' 'Nepal' 'Gambia'
 'Gabon' 'Togo' 'Indonesia' 'Namibia' 'Malawi' 'Swaziland' 'Sri Lanka'
 'Angola' 'Oman' 'Vietnam' 'Cambodia' 'Kuwait' 'Syria' 'Republic of Congo'
 'Guinea-Bissau' 'Sierra Leone' 'Eritrea' 'Djibouti' 'Lesotho' 'Laos'
 'United Arab Emirates' 'Qatar' 'Botswana' 'Pakistan ']

In [9]:
#limit columns to data useful for the project
conflicts = conflicts_df[['data_id','event_id_no_cnty','event_date','year','event_type','actor1','interaction','region','country','location','latitude','longitude','source','notes','fatalities','iso3']]
conflicts.head()

,data_id,event_id_no_cnty,event_date,year,event_type,actor1,interaction,region,country,location,latitude,longitude,source,notes,fatalities,iso3
0,686727,1469.0,2018-02-17,2018,Remote violence,PKK: Kurdistan Workers Party,12,Middle East,Turkey,Semdinli,37.3051,44.5742,Beyaz Gazete,"Reported on Saturday, 17 Febraury 2017, 1 Turk...",1,TUR
1,685529,11980.0,2018-02-17,2018,Violence against civilians,ADF: Allied Democratic Forces,27,Middle Africa,Democratic Republic of Congo,Eringiti,0.8519,29.6124,Agence France Presse; Xinhua,5 people were killed during an ambush on a civ...,5,COD
2,685530,11979.0,2018-02-17,2018,Riots/Protests,Rioters (Democratic Republic of Congo),15,Middle Africa,Democratic Republic of Congo,Ango,4.0296,25.8471,Radio Okapi,"On February 17, the population from Ango rebel...",0,COD
3,685686,6702.0,2018-02-17,2018,Remote violence,Unidentified Armed Group (Libya),37,Northern Africa,Libya,Buatni,32.0984,20.1767,Alwasat,Four civilians were wounded by the explosion o...,0,LBY
4,685687,6703.0,2018-02-17,2018,Violence against civilians,Unidentified Armed Group (Libya),37,Northern Africa,Libya,Jalu,29.0333,21.5500,Alwasat,Unknown gunmen set up a fake checkpoint and ab...,0,LBY

In [10]:
# summary, avg, etc of all numerical data
conflicts.describe()

,data_id,event_id_no_cnty,year,interaction,latitude,longitude,fatalities
count,252869.000000,252859.000000,252869.000000,252869.000000,252869.000000,252869.000000,252869.000000
mean,495752.979254,7196.633175,2012.452183,34.217097,14.321305,37.167958,3.574578
std,162304.236278,8386.790443,5.472102,20.668839,17.650830,23.176012,61.729944
min,87075.000000,1.000000,1997.000000,10.000000,-34.710100,-17.464600,0.000000
25%,370029.000000,1446.000000,2011.000000,13.000000,2.150000,25.355900,0.000000
50%,559919.000000,4138.000000,2014.000000,30.000000,13.102700,35.890800,0.000000
75%,623907.000000,9112.000000,2017.000000,60.000000,31.549700,45.400000,1.000000
max,687325.000000,39438.000000,2018.000000,88.000000,43.568900,140.718000,25000.000000

In [11]:
#narrow down data to the most useful for the project
conflict_summary = conflicts[['event_date','event_type','region','country','location','latitude','longitude','fatalities','actor1']]
conflict_summary.head()

,event_date,event_type,region,country,location,latitude,longitude,fatalities,actor1
0,2018-02-17,Remote violence,Middle East,Turkey,Semdinli,37.3051,44.5742,1,PKK: Kurdistan Workers Party
1,2018-02-17,Violence against civilians,Middle Africa,Democratic Republic of Congo,Eringiti,0.8519,29.6124,5,ADF: Allied Democratic Forces
2,2018-02-17,Riots/Protests,Middle Africa,Democratic Republic of Congo,Ango,4.0296,25.8471,0,Rioters (Democratic Republic of Congo)
3,2018-02-17,Remote violence,Northern Africa,Libya,Buatni,32.0984,20.1767,0,Unidentified Armed Group (Libya)
4,2018-02-17,Violence against civilians,Northern Africa,Libya,Jalu,29.0333,21.5500,0,Unidentified Armed Group (Libya)

In [12]:
# Rename columns
conflict_summary = conflict_summary.rename(columns={'event_date': 'Date', 'event_type': 'Conflict Type', 'region': 'Region', 'country': 'Country', 'location': 'Location', 'latitude': 'Latitude', 'longitude': 'Longitude', 'actor1': 'Actor'})
conflict_summary.head(10)

,Date,Conflict Type,Region,Country,Location,Latitude,Longitude,fatalities,Actor
0,2018-02-17,Remote violence,Middle East,Turkey,Semdinli,37.3051,44.5742,1,PKK: Kurdistan Workers Party
1,2018-02-17,Violence against civilians,Middle Africa,Democratic Republic of Congo,Eringiti,0.8519,29.6124,5,ADF: Allied Democratic Forces
2,2018-02-17,Riots/Protests,Middle Africa,Democratic Republic of Congo,Ango,4.0296,25.8471,0,Rioters (Democratic Republic of Congo)
3,2018-02-17,Remote violence,Northern Africa,Libya,Buatni,32.0984,20.1767,0,Unidentified Armed Group (Libya)
4,2018-02-17,Violence against civilians,Northern Africa,Libya,Jalu,29.0333,21.5500,0,Unidentified Armed Group (Libya)
5,2018-02-17,Battle-No change of territory,Western Africa,Mali,Hombori,15.2790,-1.7004,0,Unidentified Armed Group (Mali)
6,2018-02-17,Battle-No change of territory,Western Africa,Mali,Ahina,16.4992,0.6531,10,Unidentified Armed Group (Mali)
7,2018-02-17,Battle-No change of territory,Western Africa,Mali,Igharghar,19.8336,0.8683,5,Military Forces of France
8,2018-02-17,Battle-No change of territory,Northern Africa,Sudan,Edd Al Fursan,11.5060,24.3153,0,RSF: Rapid Support Forces
9,2018-02-17,Strategic development,Northern Africa,Egypt,Al Arish,31.1316,33.7984,0,Military Forces of Egypt (2014-)

In [13]:
#save to CSV
conflict_summary.to_csv('conflicts.csv')

In [ ]:
# conflicts.csv is too enormous to upload to GitHub.  It can be found at 
#https://drive.google.com/open?id=123cLPMHQNYBvvFCK1hmd1HZdAJ65bZ4Y