In [17]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect
import pandas as pd
import numpy as np
import json

In [18]:
!ls

app.py
data_engineering.ipynb
data_engineering_updated.ipynb
flask_queries.ipynb
info_data
raw_data
README.md
refugees_and_conflict.sqlite
templates

In [19]:
engine = create_engine('sqlite:///refugees_and_conflict.sqlite')

In [20]:
Base = automap_base()

In [21]:
Base.prepare(engine, reflect = True)

In [22]:
Base.classes.keys()

['asylum', 'battle_deaths', 'info_table', 'origin']

In [23]:
session = Session(engine)

In [32]:
Asylum = Base.classes.asylum
BattleDeaths = Base.classes.battle_deaths
Origin = Base.classes.origin
InfoTable = Base.classes.info_table

In [25]:
samples_df = pd.read_sql_table('asylum', engine)
samples_df.head()

,id,country_name,country_lat,country_lon,country_code,y1990,y1991,y1992,y1993,y1994,...,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016,y2017
0,1,Albania,41.0000,20.0,ALB,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Algeria,28.0000,3.0,DZA,0,34,257,800,1916,...,339,505,236,267,256,147,107,110,86,0
2,3,American Samoa,-14.3333,-170.0,ASM,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Andorra,42.5000,1.6,AND,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Angola,-12.5000,18.5,AGO,2558,526,2321,12054,3974,...,0,25,0,0,0,0,0,0,0,0

## Query Country Names

In [26]:
country_names = session.query(Asylum.country_name).all()
country_names = [x[0] for x in country_names]
country_names

['Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Polynesia',
 'Gabon',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Zambia',
 'Zimbabwe',
 'Afghanistan']

## Query Info Table

In [27]:
samples_df = pd.read_sql_table('info_table', engine)
samples_df.head()

,id,country_name,gdp_YR2015,population_YR2016,asylum_YR2016,origin_YR2016
0,1,Afghanistan,19215562178.9798,34656,17980,2501410
1,2,Albania,11335264966.561,2876,0,11050
2,3,Algeria,165874330876.321,40606,86,3675
3,4,American Samoa,659000000,56,0,0
4,5,Andorra,2811489408.89431,77,0,0

In [48]:
first_row_samples = session.query(InfoTable).first()
first_row_samples.__dict__

{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState at 0x169d05c3240>,
 'asylum_YR2016': 17980,
 'country_name': 'Afghanistan',
 'gdp_YR2015': '19215562178.9798',
 'id': 1,
 'origin_YR2016': 2501410,
 'population_YR2016': '34656'}

In [49]:
info_table = session.query(InfoTable.country_name, InfoTable.gdp_YR2015, InfoTable.population_YR2016, 
                           InfoTable.asylum_YR2016, InfoTable.origin_YR2016).all()

In [50]:
info_table = pd.DataFrame(info_table)
info_table.head()

,country_name,gdp_YR2015,population_YR2016,asylum_YR2016,origin_YR2016
0,Afghanistan,19215562178.9798,34656,17980,2501410
1,Albania,11335264966.561,2876,0,11050
2,Algeria,165874330876.321,40606,86,3675
3,American Samoa,659000000,56,0,0
4,Andorra,2811489408.89431,77,0,0

In [51]:
info_table = info_table.set_index('country_name').to_dict('index')

In [52]:
info_table

{'Afghanistan': {'asylum_YR2016': 17980,
  'gdp_YR2015': '19215562178.9798',
  'origin_YR2016': 2501410,
  'population_YR2016': '34656'},
 'Albania': {'asylum_YR2016': 0,
  'gdp_YR2015': '11335264966.561',
  'origin_YR2016': 11050,
  'population_YR2016': '2876'},
 'Algeria': {'asylum_YR2016': 86,
  'gdp_YR2015': '165874330876.321',
  'origin_YR2016': 3675,
  'population_YR2016': '40606'},
 'American Samoa': {'asylum_YR2016': 0,
  'gdp_YR2015': '659000000',
  'origin_YR2016': 0,
  'population_YR2016': '56'},
 'Andorra': {'asylum_YR2016': 0,
  'gdp_YR2015': '2811489408.89431',
  'origin_YR2016': 0,
  'population_YR2016': '77'},
 'Angola': {'asylum_YR2016': 0,
  'gdp_YR2015': '102962245246.708',
  'origin_YR2016': 8363,
  'population_YR2016': '28813'},
 'Antigua and Barbuda': {'asylum_YR2016': 0,
  'gdp_YR2015': '1364863037.03704',
  'origin_YR2016': 77,
  'population_YR2016': '101'},
 'Argentina': {'asylum_YR2016': 0,
  'gdp_YR2015': '584711485367.267',
  'origin_YR2016': 115,
  'population_YR2016': '43847'},
 'Armenia': {'asylum_YR2016': 4,
  'gdp_YR2015': '10553337672.9872',
  'origin_YR2016': 10687,
  'population_YR2016': '2925'},
 'Aruba': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 0,
  'population_YR2016': '105'},
 'Australia': {'asylum_YR2016': 0,
  'gdp_YR2015': '1345383143356.35',
  'origin_YR2016': 0,
  'population_YR2016': '24127'},
 'Austria': {'asylum_YR2016': 0,
  'gdp_YR2015': '382065930307.978',
  'origin_YR2016': 0,
  'population_YR2016': '8747'},
 'Azerbaijan': {'asylum_YR2016': 137,
  'gdp_YR2015': '53074370486.0433',
  'origin_YR2016': 10087,
  'population_YR2016': '9762'},
 'Bahamas, The': {'asylum_YR2016': 0,
  'gdp_YR2015': '11240000000',
  'origin_YR2016': 293,
  'population_YR2016': '391'},
 'Bahrain': {'asylum_YR2016': 0,
  'gdp_YR2015': '31125851063.8298',
  'origin_YR2016': 446,
  'population_YR2016': '1425'},
 'Bangladesh': {'asylum_YR2016': 39,
  'gdp_YR2015': '195078665827.565',
  'origin_YR2016': 13810,
  'population_YR2016': '162952'},
 'Barbados': {'asylum_YR2016': 0,
  'gdp_YR2015': '4584150000',
  'origin_YR2016': 144,
  'population_YR2016': '285'},
 'Belarus': {'asylum_YR2016': 0,
  'gdp_YR2015': '56454734396.5842',
  'origin_YR2016': 3824,
  'population_YR2016': '9507'},
 'Belgium': {'asylum_YR2016': 2,
  'gdp_YR2015': '455200045095.643',
  'origin_YR2016': 44,
  'population_YR2016': '11348'},
 'Belize': {'asylum_YR2016': 0,
  'gdp_YR2015': '1742545900',
  'origin_YR2016': 53,
  'population_YR2016': '367'},
 'Benin': {'asylum_YR2016': 0,
  'gdp_YR2015': '8290986804.45245',
  'origin_YR2016': 464,
  'population_YR2016': '10872'},
 'Bermuda': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 0,
  'population_YR2016': '65'},
 'Bhutan': {'asylum_YR2016': 0,
  'gdp_YR2015': '2059258652.94668',
  'origin_YR2016': 11732,
  'population_YR2016': '798'},
 'Bolivia': {'asylum_YR2016': 0,
  'gdp_YR2015': '33000198263.3864',
  'origin_YR2016': 515,
  'population_YR2016': '10888'},
 'Bosnia and Herzegovina': {'asylum_YR2016': 0,
  'gdp_YR2015': '16209702863.6235',
  'origin_YR2016': 18179,
  'population_YR2016': '3517'},
 'Botswana': {'asylum_YR2016': 0,
  'gdp_YR2015': '14430573505.3797',
  'origin_YR2016': 265,
  'population_YR2016': '2250'},
 'Brazil': {'asylum_YR2016': 0,
  'gdp_YR2015': '1803652649613.75',
  'origin_YR2016': 793,
  'population_YR2016': '207653'},
 'British Virgin Islands': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 0,
  'population_YR2016': '31'},
 'Brunei Darussalam': {'asylum_YR2016': 0,
  'gdp_YR2015': '12930394937.8137',
  'origin_YR2016': 0,
  'population_YR2016': '423'},
 'Bulgaria': {'asylum_YR2016': 0,
  'gdp_YR2015': '50199117547.0415',
  'origin_YR2016': 794,
  'population_YR2016': '7128'},
 'Burkina Faso': {'asylum_YR2016': 0,
  'gdp_YR2015': '10419303761.3524',
  'origin_YR2016': 2327,
  'population_YR2016': '18646'},
 'Burundi': {'asylum_YR2016': 0,
  'gdp_YR2015': '3066681386.73841',
  'origin_YR2016': 408036,
  'population_YR2016': '10524'},
 'Cabo Verde': {'asylum_YR2016': 0,
  'gdp_YR2015': '1574288667.69981',
  'origin_YR2016': 0,
  'population_YR2016': '540'},
 'Cambodia': {'asylum_YR2016': 0,
  'gdp_YR2015': '18049954289.4229',
  'origin_YR2016': 12408,
  'population_YR2016': '15762'},
 'Cameroon': {'asylum_YR2016': 181,
  'gdp_YR2015': '30916218544.4404',
  'origin_YR2016': 10328,
  'population_YR2016': '23439'},
 'Canada': {'asylum_YR2016': 0,
  'gdp_YR2015': '1552807652015.37',
  'origin_YR2016': 76,
  'population_YR2016': '36286'},
 'Cayman Islands': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 6,
  'population_YR2016': '61'},
 'Central African Republic': {'asylum_YR2016': 0,
  'gdp_YR2015': '1583776759.97697',
  'origin_YR2016': 490869,
  'population_YR2016': '4595'},
 'Chad': {'asylum_YR2016': 0,
  'gdp_YR2015': '10888798113.7866',
  'origin_YR2016': 14146,
  'population_YR2016': '14453'},
 'Channel Islands': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 0,
  'population_YR2016': '165'},
 'Chile': {'asylum_YR2016': 0,
  'gdp_YR2015': '242517905161.664',
  'origin_YR2016': 490,
  'population_YR2016': '17910'},
 'China': {'asylum_YR2016': 0,
  'gdp_YR2015': '11064666282625.5',
  'origin_YR2016': 207733,
  'population_YR2016': '1378665'},
 'Colombia': {'asylum_YR2016': 30,
  'gdp_YR2015': '291519596338.693',
  'origin_YR2016': 311051,
  'population_YR2016': '48653'},
 'Comoros': {'asylum_YR2016': 0,
  'gdp_YR2015': '565689764.63263',
  'origin_YR2016': 557,
  'population_YR2016': '796'},
 'Congo, Dem. Rep.': {'asylum_YR2016': 261,
  'gdp_YR2015': '36188521106.9294',
  'origin_YR2016': 537429,
  'population_YR2016': '78736'},
 'Congo, Rep.': {'asylum_YR2016': 51,
  'gdp_YR2015': '8553154580.39951',
  'origin_YR2016': 13231,
  'population_YR2016': '5126'},
 'Costa Rica': {'asylum_YR2016': 0,
  'gdp_YR2015': '54840103850.265',
  'origin_YR2016': 197,
  'population_YR2016': '4857'},
 'Croatia': {'asylum_YR2016': 0,
  'gdp_YR2015': '48921877447.764',
  'origin_YR2016': 26211,
  'population_YR2016': '4171'},
 'Cuba': {'asylum_YR2016': 0,
  'gdp_YR2015': '87132800000',
  'origin_YR2016': 5925,
  'population_YR2016': '11476'},
 'Cyprus': {'asylum_YR2016': 0,
  'gdp_YR2015': '19676167239.6584',
  'origin_YR2016': 0,
  'population_YR2016': '1170'},
 'Czech Republic': {'asylum_YR2016': 0,
  'gdp_YR2015': '186829940545.759',
  'origin_YR2016': 1266,
  'population_YR2016': '10562'},
 'Denmark': {'asylum_YR2016': 0,
  'gdp_YR2015': '301298464861.385',
  'origin_YR2016': 0,
  'population_YR2016': '5731'},
 'Djibouti': {'asylum_YR2016': 0,
  'gdp_YR2015': '1727000000',
  'origin_YR2016': 1417,
  'population_YR2016': '942'},
 'Dominica': {'asylum_YR2016': 0,
  'gdp_YR2015': '535095846.296296',
  'origin_YR2016': 20,
  'population_YR2016': '74'},
 'Dominican Republic': {'asylum_YR2016': 0,
  'gdp_YR2015': '68102618092.1031',
  'origin_YR2016': 344,
  'population_YR2016': '10649'},
 'Ecuador': {'asylum_YR2016': 0,
  'gdp_YR2015': '99290381000',
  'origin_YR2016': 1021,
  'population_YR2016': '16385'},
 'Egypt, Arab Rep.': {'asylum_YR2016': 268,
  'gdp_YR2015': '332698041030.807',
  'origin_YR2016': 19742,
  'population_YR2016': '95689'},
 'El Salvador': {'asylum_YR2016': 0,
  'gdp_YR2015': '26052340000',
  'origin_YR2016': 19595,
  'population_YR2016': '6345'},
 'Equatorial Guinea': {'asylum_YR2016': 0,
  'gdp_YR2015': '12597210657.5048',
  'origin_YR2016': 126,
  'population_YR2016': '1221'},
 'Eritrea': {'asylum_YR2016': 25,
  'gdp_YR2015': '0',
  'origin_YR2016': 459390,
  'population_YR2016': '4955'},
 'Estonia': {'asylum_YR2016': 0,
  'gdp_YR2015': '22566956982.229',
  'origin_YR2016': 298,
  'population_YR2016': '1316'},
 'Ethiopia': {'asylum_YR2016': 50,
  'gdp_YR2015': '64464547915.2698',
  'origin_YR2016': 83894,
  'population_YR2016': '102403'},
 'Faroe Islands': {'asylum_YR2016': 0,
  'gdp_YR2015': '2476746087.18917',
  'origin_YR2016': 0,
  'population_YR2016': '49'},
 'Fiji': {'asylum_YR2016': 0,
  'gdp_YR2015': '4391113415.33181',
  'origin_YR2016': 791,
  'population_YR2016': '899'},
 'Finland': {'asylum_YR2016': 0,
  'gdp_YR2015': '232439324529.645',
  'origin_YR2016': 0,
  'population_YR2016': '5495'},
 'France': {'asylum_YR2016': 0,
  'gdp_YR2015': '2433562015516.21',
  'origin_YR2016': 45,
  'population_YR2016': '66896'},
 'French Polynesia': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 0,
  'population_YR2016': '280'},
 'Gabon': {'asylum_YR2016': 0,
  'gdp_YR2015': '14262032470.9041',
  'origin_YR2016': 152,
  'population_YR2016': '1980'},
 'Gambia, The': {'asylum_YR2016': 0,
  'gdp_YR2015': '907652509.516259',
  'origin_YR2016': 11569,
  'population_YR2016': '2039'},
 'Georgia': {'asylum_YR2016': 0,
  'gdp_YR2015': '13993546732.4726',
  'origin_YR2016': 6365,
  'population_YR2016': '3719'},
 'Germany': {'asylum_YR2016': 0,
  'gdp_YR2015': '3375611100742.22',
  'origin_YR2016': 67,
  'population_YR2016': '82668'},
 'Ghana': {'asylum_YR2016': 0,
  'gdp_YR2015': '37543361203.5609',
  'origin_YR2016': 15507,
  'population_YR2016': '28207'},
 'Gibraltar': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 0,
  'population_YR2016': '34'},
 'Greece': {'asylum_YR2016': 0,
  'gdp_YR2015': '195541761243.144',
  'origin_YR2016': 101,
  'population_YR2016': '10747'},
 'Greenland': {'asylum_YR2016': 0,
  'gdp_YR2015': '2220380802.33059',
  'origin_YR2016': 0,
  'population_YR2016': '56'},
 'Grenada': {'asylum_YR2016': 0,
  'gdp_YR2015': '997007925.925926',
  'origin_YR2016': 100,
  'population_YR2016': '107'},
 'Guam': {'asylum_YR2016': 0,
  'gdp_YR2015': '5697000000',
  'origin_YR2016': 0,
  'population_YR2016': '163'},
 'Guatemala': {'asylum_YR2016': 0,
  'gdp_YR2015': '63767597193.9175',
  'origin_YR2016': 12534,
  'population_YR2016': '16582'},
 'Guinea': {'asylum_YR2016': 0,
  'gdp_YR2015': '8767143622.83101',
  'origin_YR2016': 17526,
  'population_YR2016': '12396'},
 'Guinea-Bissau': {'asylum_YR2016': 0,
  'gdp_YR2015': '1036130506.53639',
  'origin_YR2016': 1635,
  'population_YR2016': '1816'},
 'Guyana': {'asylum_YR2016': 0,
  'gdp_YR2015': '3197225181.59806',
  'origin_YR2016': 269,
  'population_YR2016': '773'},
 'Haiti': {'asylum_YR2016': 0,
  'gdp_YR2015': '8724656126.49849',
  'origin_YR2016': 29661,
  'population_YR2016': '10847'},
 'Honduras': {'asylum_YR2016': 0,
  'gdp_YR2015': '20844284855.0025',
  'origin_YR2016': 10479,
  'population_YR2016': '9113'},
 'Hong Kong SAR, China': {'asylum_YR2016': 0,
  'gdp_YR2015': '309403880389.071',
  'origin_YR2016': 5,
  'population_YR2016': '7347'},
 'Hungary': {'asylum_YR2016': 0,
  'gdp_YR2015': '122879042001.915',
  'origin_YR2016': 2904,
  'population_YR2016': '9818'},
 'Iceland': {'asylum_YR2016': 0,
  'gdp_YR2015': '16783714958.4498',
  'origin_YR2016': 0,
  'population_YR2016': '334'},
 'India': {'asylum_YR2016': 652,
  'gdp_YR2015': '2089865410867.82',
  'origin_YR2016': 7243,
  'population_YR2016': '1324171'},
 'Indonesia': {'asylum_YR2016': 0,
  'gdp_YR2015': '861256351277.359',
  'origin_YR2016': 13046,
  'population_YR2016': '261115'},
 'Iran, Islamic Rep.': {'asylum_YR2016': 0,
  'gdp_YR2015': '385874474398.59',
  'origin_YR2016': 94042,
  'population_YR2016': '80277'},
 'Iraq': {'asylum_YR2016': 9016,
  'gdp_YR2015': '179640210726.448',
  'origin_YR2016': 315998,
  'population_YR2016': '37203'},
 'Ireland': {'asylum_YR2016': 0,
  'gdp_YR2015': '290617006703.972',
  'origin_YR2016': 0,
  'population_YR2016': '4773'},
 'Isle of Man': {'asylum_YR2016': 0,
  'gdp_YR2015': '6792417112.29947',
  'origin_YR2016': 0,
  'population_YR2016': '84'},
 'Israel': {'asylum_YR2016': 0,
  'gdp_YR2015': '299096404728.826',
  'origin_YR2016': 467,
  'population_YR2016': '8547'},
 'Italy': {'asylum_YR2016': 0,
  'gdp_YR2015': '1832347450961.51',
  'origin_YR2016': 44,
  'population_YR2016': '60601'},
 'Jamaica': {'asylum_YR2016': 0,
  'gdp_YR2015': '14186886642.6685',
  'origin_YR2016': 1988,
  'population_YR2016': '2881'},
 'Japan': {'asylum_YR2016': 0,
  'gdp_YR2015': '4383076298081.86',
  'origin_YR2016': 53,
  'population_YR2016': '126995'},
 'Jordan': {'asylum_YR2016': 34,
  'gdp_YR2015': '37517410281.6901',
  'origin_YR2016': 1889,
  'population_YR2016': '9456'},
 'Kazakhstan': {'asylum_YR2016': 0,
  'gdp_YR2015': '184388432148.715',
  'origin_YR2016': 2326,
  'population_YR2016': '17797'},
 'Kenya': {'asylum_YR2016': 49,
  'gdp_YR2015': '63767539356.6051',
  'origin_YR2016': 7506,
  'population_YR2016': '48462'},
 'Kiribati': {'asylum_YR2016': 0,
  'gdp_YR2015': '169140538.696106',
  'origin_YR2016': 0,
  'population_YR2016': '114'},
 'Korea, Rep.': {'asylum_YR2016': 0,
  'gdp_YR2015': '1382764027113.82',
  'origin_YR2016': 243,
  'population_YR2016': '51246'},
 'Kosovo': {'asylum_YR2016': 0,
  'gdp_YR2015': '6440501275.36875',
  'origin_YR2016': 0,
  'population_YR2016': '1816'},
 'Kuwait': {'asylum_YR2016': 0,
  'gdp_YR2015': '114567298105.683',
  'origin_YR2016': 1008,
  'population_YR2016': '4053'},
 'Kyrgyz Republic': {'asylum_YR2016': 0,
  'gdp_YR2015': '6678178340.45121',
  'origin_YR2016': 2546,
  'population_YR2016': '6083'},
 'Lao PDR': {'asylum_YR2016': 0,
  'gdp_YR2015': '14390391264.2607',
  'origin_YR2016': 7224,
  'population_YR2016': '6758'},
 'Latvia': {'asylum_YR2016': 0,
  'gdp_YR2015': '27009231911.4428',
  'origin_YR2016': 165,
  'population_YR2016': '1960'},
 'Lebanon': {'asylum_YR2016': 0,
  'gdp_YR2015': '49459296463.2836',
  'origin_YR2016': 4709,
  'population_YR2016': '6007'},
 'Lesotho': {'asylum_YR2016': 0,
  'gdp_YR2015': '2505886024.6573',
  'origin_YR2016': 5,
  'population_YR2016': '2204'},
 'Liberia': {'asylum_YR2016': 0,
  'gdp_YR2015': '2034000000',
  'origin_YR2016': 6513,
  'population_YR2016': '4614'},
 'Libya': {'asylum_YR2016': 1727,
  'gdp_YR2015': '0',
  'origin_YR2016': 8796,
  'population_YR2016': '6293'},
 'Liechtenstein': {'asylum_YR2016': 0,
  'gdp_YR2015': '6289165409.55908',
  'origin_YR2016': 0,
  'population_YR2016': '38'},
 'Lithuania': {'asylum_YR2016': 0,
  'gdp_YR2015': '41402022148.2053',
  'origin_YR2016': 64,
  'population_YR2016': '2872'},
 'Luxembourg': {'asylum_YR2016': 0,
  'gdp_YR2015': '57784495265.4378',
  'origin_YR2016': 0,
  'population_YR2016': '583'},
 'Macao SAR, China': {'asylum_YR2016': 0,
  'gdp_YR2015': '45361678146.5247',
  'origin_YR2016': 0,
  'population_YR2016': '612'},
 'Macedonia, FYR': {'asylum_YR2016': 0,
  'gdp_YR2015': '10051659161.1733',
  'origin_YR2016': 1705,
  'population_YR2016': '2081'},
 'Madagascar': {'asylum_YR2016': 0,
  'gdp_YR2015': '9744243420.48073',
  'origin_YR2016': 277,
  'population_YR2016': '24895'},
 'Malawi': {'asylum_YR2016': 0,
  'gdp_YR2015': '6373201160.03248',
  'origin_YR2016': 407,
  'population_YR2016': '18092'},
 'Malaysia': {'asylum_YR2016': 0,
  'gdp_YR2015': '296434003328.639',
  'origin_YR2016': 443,
  'population_YR2016': '31187'},
 'Maldives': {'asylum_YR2016': 0,
  'gdp_YR2015': '4006531188.26486',
  'origin_YR2016': 48,
  'population_YR2016': '417'},
 'Mali': {'asylum_YR2016': 96,
  'gdp_YR2015': '13100058099.804',
  'origin_YR2016': 156390,
  'population_YR2016': '17995'},
 'Malta': {'asylum_YR2016': 0,
  'gdp_YR2015': '10285547954.0777',
  'origin_YR2016': 0,
  'population_YR2016': '437'},
 'Marshall Islands': {'asylum_YR2016': 0,
  'gdp_YR2015': '179697900',
  'origin_YR2016': 0,
  'population_YR2016': '53'},
 'Mauritania': {'asylum_YR2016': 0,
  'gdp_YR2015': '4844223106.95469',
  'origin_YR2016': 36228,
  'population_YR2016': '4301'},
 'Mauritius': {'asylum_YR2016': 0,
  'gdp_YR2015': '11692287066.381',
  'origin_YR2016': 101,
  'population_YR2016': '1263'},
 'Mexico': {'asylum_YR2016': 0,
  'gdp_YR2015': '1152263780657.86',
  'origin_YR2016': 10367,
  'population_YR2016': '127540'},
 'Micronesia, Fed. Sts.': {'asylum_YR2016': 0,
  'gdp_YR2015': '315179700',
  'origin_YR2016': 0,
  'population_YR2016': '105'},
 'Moldova': {'asylum_YR2016': 0,
  'gdp_YR2015': '6512899540.34594',
  'origin_YR2016': 2291,
  'population_YR2016': '3552'},
 'Monaco': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 0,
  'population_YR2016': '38'},
 'Mongolia': {'asylum_YR2016': 0,
  'gdp_YR2015': '11749620619.5962',
  'origin_YR2016': 2267,
  'population_YR2016': '3027'},
 'Montenegro': {'asylum_YR2016': 0,
  'gdp_YR2015': '4052913385.82677',
  'origin_YR2016': 708,
  'population_YR2016': '623'},
 'Morocco': {'asylum_YR2016': 0,
  'gdp_YR2015': '101187079462.942',
  'origin_YR2016': 2230,
  'population_YR2016': '35277'},
 'Mozambique': {'asylum_YR2016': 26,
  'gdp_YR2015': '14798439527.2541',
  'origin_YR2016': 33,
  'population_YR2016': '28829'},
 'Myanmar': {'asylum_YR2016': 116,
  'gdp_YR2015': '59687373958.2574',
  'origin_YR2016': 490265,
  'population_YR2016': '52885'},
 'Namibia': {'asylum_YR2016': 0,
  'gdp_YR2015': '11571141027.0478',
  'origin_YR2016': 1348,
  'population_YR2016': '2480'},
 'Nauru': {'asylum_YR2016': 0,
  'gdp_YR2015': '100459782.608696',
  'origin_YR2016': 0,
  'population_YR2016': '13'},
 'Nepal': {'asylum_YR2016': 0,
  'gdp_YR2015': '21410840908.5198',
  'origin_YR2016': 8350,
  'population_YR2016': '28983'},
 'Netherlands': {'asylum_YR2016': 0,
  'gdp_YR2015': '757999453314.269',
  'origin_YR2016': 27,
  'population_YR2016': '17018'},
 'New Caledonia': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 0,
  'population_YR2016': '278'},
 'New Zealand': {'asylum_YR2016': 0,
  'gdp_YR2015': '175562976175.285',
  'origin_YR2016': 25,
  'population_YR2016': '4693'},
 'Nicaragua': {'asylum_YR2016': 0,
  'gdp_YR2015': '12747741539.7259',
  'origin_YR2016': 1409,
  'population_YR2016': '6150'},
 'Niger': {'asylum_YR2016': 274,
  'gdp_YR2015': '0',
  'origin_YR2016': 1210,
  'population_YR2016': '20673'},
 'Nigeria': {'asylum_YR2016': 2430,
  'gdp_YR2015': '481066152889.094',
  'origin_YR2016': 229261,
  'population_YR2016': '185990'},
 'Northern Mariana Islands': {'asylum_YR2016': 0,
  'gdp_YR2015': '933000000',
  'origin_YR2016': 0,
  'population_YR2016': '55'},
 'Norway': {'asylum_YR2016': 0,
  'gdp_YR2015': '386663139402.707',
  'origin_YR2016': 0,
  'population_YR2016': '5233'},
 'Oman': {'asylum_YR2016': 0,
  'gdp_YR2015': '69831770871.2614',
  'origin_YR2016': 20,
  'population_YR2016': '4425'},
 'Pakistan': {'asylum_YR2016': 761,
  'gdp_YR2015': '270556126820.064',
  'origin_YR2016': 105376,
  'population_YR2016': '193203'},
 'Palau': {'asylum_YR2016': 0,
  'gdp_YR2015': '297645400',
  'origin_YR2016': 0,
  'population_YR2016': '22'},
 'Panama': {'asylum_YR2016': 0,
  'gdp_YR2015': '52132289700',
  'origin_YR2016': 33,
  'population_YR2016': '4034'},
 'Papua New Guinea': {'asylum_YR2016': 0,
  'gdp_YR2015': '21060901603.8145',
  'origin_YR2016': 391,
  'population_YR2016': '8085'},
 'Paraguay': {'asylum_YR2016': 0,
  'gdp_YR2015': '27282581335.7964',
  'origin_YR2016': 63,
  'population_YR2016': '6725'},
 'Peru': {'asylum_YR2016': 0,
  'gdp_YR2015': '189212096470.293',
  'origin_YR2016': 2589,
  'population_YR2016': '31774'},
 'Philippines': {'asylum_YR2016': 414,
  'gdp_YR2015': '292774099013.687',
  'origin_YR2016': 421,
  'population_YR2016': '103320'},
 'Poland': {'asylum_YR2016': 0,
  'gdp_YR2015': '477279647754.701',
  'origin_YR2016': 1144,
  'population_YR2016': '37948'},
 'Portugal': {'asylum_YR2016': 0,
  'gdp_YR2015': '199420256049.689',
  'origin_YR2016': 5,
  'population_YR2016': '10325'},
 'Puerto Rico': {'asylum_YR2016': 0,
  'gdp_YR2015': '0',
  'origin_YR2016': 0,
  'population_YR2016': '3411'},
 'Qatar': {'asylum_YR2016': 0,
  'gdp_YR2015': '164641483516.484',
  'origin_YR2016': 20,
  'population_YR2016': '2570'},
 'Romania': {'asylum_YR2016': 0,
  'gdp_YR2015': '177911101680.106',
  'origin_YR2016': 1190,
  'population_YR2016': '19705'},
 'Russian Federation': {'asylum_YR2016': 66,
  'gdp_YR2015': '1365864126832.81',
  'origin_YR2016': 62737,
  'population_YR2016': '144342'},
 'Rwanda': {'asylum_YR2016': 0,
  'gdp_YR2015': '8261034257.63248',
  'origin_YR2016': 286033,
  'population_YR2016': '11918'},