In [168]:
# import dependencies
import pandas as pd
import os

import sqlalchemy
from sqlalchemy import create_engine, MetaData
import pymysql
pymysql.install_as_MySQLdb()

# Import and establish Base for which classes will be constructed 
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

from sqlalchemy import Column, Integer, String, Numeric, Text, Float

In [169]:
!ls

app.py
data_engineering.ipynb
data_engineering_updated.ipynb
flask_queries.ipynb
GitHub
raw_data
README.md
refugees_and_conflict.sqlite
templates
Untitled.ipynb

In [170]:
!rm refugees_and_conflict.sqlite

rm: cannot remove 'refugees_and_conflict.sqlite': Device or resource busy

In [171]:
# load data into pandas dataframes
battle_deaths_file = os.path.join("raw_data", "battle_deaths_by_country_merged.csv")

In [172]:
battle_deaths_data = pd.read_csv(battle_deaths_file)

In [173]:
len(battle_deaths_data)

181

In [174]:
battle_deaths_data = battle_deaths_data.replace(to_replace="..", value=0)

In [175]:
battle_deaths_data = battle_deaths_data.drop(['Series Name','Series Code'], axis=1)

In [176]:
column_names = ["country_name","country_lat", "country_lon", "country_code"]
for year in range(1990,2018):
    column_names.append('y' + str(year))

In [177]:
battle_deaths_data.columns = column_names

In [178]:
battle_deaths_data

,country_name,country_lat,country_lon,country_code,y1990,y1991,y1992,y1993,y1994,y1995,...,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016,y2017
0,Albania,41.0000,20.0000,ALB,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Algeria,28.0000,3.0000,DZA,0,34,257,800,1916,3008,...,339,505,236,267,256,147,107,110,86,0
2,American Samoa,-14.3333,-170.0000,ASM,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Andorra,42.5000,1.6000,AND,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Angola,-12.5000,18.5000,AGO,2558,526,2321,12054,3974,162,...,0,25,0,0,0,0,0,0,0,0
5,Antigua and Barbuda,17.0500,-61.8000,ATG,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Argentina,-34.0000,-64.0000,ARG,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,Armenia,40.0000,45.0000,ARM,0,0,85,37,30,0,...,0,0,0,0,9,0,0,9,4,0
8,Aruba,12.5000,-69.9667,ABW,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Australia,-27.0000,133.0000,AUS,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Austria,47.3333,13.3333,AUT,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Azerbaijan,40.5000,47.5000,AZE,0,35,2082,1197,1477,44,...,30,0,0,0,16,0,46,63,137,0
12,Bahrain,26.0000,50.5500,BHR,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,Bangladesh,24.0000,90.0000,BGD,45,25,0,0,0,0,...,0,0,0,0,0,0,0,0,39,0
14,Barbados,13.1667,-59.5333,BRB,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,Belarus,53.0000,28.0000,BLR,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,Belgium,50.8333,4.0000,BEL,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,0
17,Belize,17.2500,-88.7500,BLZ,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,Benin,9.5000,2.2500,BEN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,Bermuda,32.3333,-64.7500,BMU,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,Bhutan,27.5000,90.5000,BTN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,Bosnia and Herzegovina,44.0000,18.0000,BIH,0,0,3972,5295,2831,1345,...,0,0,0,0,0,0,0,0,0,0
22,Botswana,-22.0000,24.0000,BWA,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Brazil,-10.0000,-55.0000,BRA,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,Brunei Darussalam,4.5000,114.6667,BRN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,Bulgaria,43.0000,25.0000,BGR,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,Burkina Faso,13.0000,-2.0000,BFA,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,Burundi,-3.5000,30.0000,BDI,0,272,61,0,56,254,...,201,0,0,0,0,0,49,133,0,0
28,Cambodia,13.0000,105.0000,KHM,274,220,118,274,464,694,...,0,0,0,10,0,0,0,0,0,0
29,Cameroon,6.0000,12.0000,CMR,0,0,0,0,0,0,...,0,0,0,0,0,0,969,924,181,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Spain,40.0000,-4.0000,ESP,0,44,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
152,Sri Lanka,7.0000,81.0000,LKA,3622,6432,4091,2075,657,4755,...,8262,10165,0,0,0,0,0,0,0,0
153,Sudan,15.0000,30.0000,SDN,5030,1313,1083,942,337,1036,...,620,373,1054,1404,1411,593,849,1264,1314,0
154,Suriname,4.0000,-56.0000,SUR,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
155,Swaziland,-26.5000,31.5000,SWZ,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
156,Sweden,62.0000,15.0000,SWE,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
157,Switzerland,47.0000,8.0000,CHE,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
158,Syrian Arab Republic,35.0000,38.0000,SYR,0,0,0,0,0,0,...,0,0,0,965,38500,69086,57529,46643,44303,0
159,Tajikistan,39.0000,71.0000,TJK,0,0,3281,1045,356,368,...,0,0,98,28,0,0,0,0,0,0
160,Thailand,15.0000,100.0000,THA,19,0,0,0,0,0,...,148,138,82,161,131,189,68,53,50,0
161,Timor-Leste,-8.5500,125.5167,TLS,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
162,Togo,8.0000,1.1667,TGO,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
163,Tonga,-20.0000,-175.0000,TON,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
164,Trinidad and Tobago,11.0000,-61.0000,TTO,39,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
165,Tunisia,34.0000,9.0000,TUN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
166,Turkey,39.0000,35.0000,TUR,245,344,1563,2117,3865,3006,...,429,126,197,421,743,19,0,899,1398,0
167,Turkmenistan,40.0000,60.0000,TKM,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
168,Turks and Caicos Islands,21.7500,-71.5833,TCA,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
169,Tuvalu,-8.0000,178.0000,TUV,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
170,Uganda,1.0000,32.0000,UGA,626,857,72,0,149,259,...,0,0,0,0,0,0,0,0,0,0
171,Ukraine,49.0000,32.0000,UKR,0,0,0,0,0,0,...,0,0,0,0,0,0,4353,1304,255,0
172,United Arab Emirates,24.0000,54.0000,ARE,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
173,United Kingdom,54.0000,-2.0000,GBR,41,26,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
174,United States,38.0000,-97.0000,USA,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
175,Uruguay,-33.0000,-56.0000,URY,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
176,Uzbekistan,41.0000,64.0000,UZB,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
177,Vanuatu,-16.0000,167.0000,VUT,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
178,Zambia,-15.0000,30.0000,ZMB,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
179,Zimbabwe,-20.0000,30.0000,ZWE,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
180,Afghanistan,33.0000,65.0000,AFG,1478,3302,4276,4071,8937,5499,...,5552,6341,6864,7405,7719,8056,12285,17273,17980,0

In [179]:
connection_string = "sqlite:///refugees_and_conflict.sqlite"
engine = create_engine(connection_string)
conn = engine.connect()

In [180]:
# create ORM classes for each table
class BattleDeaths(Base):
    __tablename__ = 'battle_deaths'

    id = Column(Integer, primary_key=True)
    country_name = Column(Text)
    country_lat = Column(Float)
    country_lon = Column(Float)
    country_code = Column(Text)
    y1990 = Column(Integer)
    y1991 = Column(Integer)
    y1992 = Column(Integer)
    y1993 = Column(Integer)
    y1994 = Column(Integer)
    y1995 = Column(Integer)
    y1996 = Column(Integer)
    y1997 = Column(Integer)
    y1998 = Column(Integer)
    y1999 = Column(Integer)
    y2000 = Column(Integer)
    y2001 = Column(Integer)
    y2002 = Column(Integer)
    y2003 = Column(Integer)
    y2004 = Column(Integer)
    y2005 = Column(Integer)
    y2006 = Column(Integer)
    y2007 = Column(Integer)
    y2008 = Column(Integer)
    y2009 = Column(Integer)
    y2010 = Column(Integer)
    y2011 = Column(Integer)
    y2012 = Column(Integer)
    y2013 = Column(Integer)
    y2014 = Column(Integer)
    y2015 = Column(Integer)
    y2016 = Column(Integer)
    y2017 = Column(Integer)        
    
    def __repr__(self):
        return f"id={self.id}, name={self.name}"

In [181]:
Base.metadata.create_all(engine)

In [182]:
# write data to tables
battle_deaths_data_to_write = battle_deaths_data.to_dict(orient='records')

In [183]:
len(battle_deaths_data_to_write)

181

In [184]:
metadata = MetaData(bind=engine)
metadata.reflect()

In [185]:
battle_deaths_table = sqlalchemy.Table('battle_deaths', metadata, autoload=False)

In [186]:
conn.execute(battle_deaths_table.insert(), battle_deaths_data_to_write)

In [187]:
# confirm data properly written to table

battle_deaths_head = conn.execute("select * from battle_deaths").fetchall()
print("First 5 rows of battle_deaths table:")
print(len(battle_deaths_head))

First 5 rows of battle_deaths table:
3160